export default {
  GET_GLOBAL_DATA: 'GET_GLOBAL_DATA',
  GET_GLOBAL_DATA_REQUEST: 'GET_GLOBAL_DATA_REQUEST',
  GET_GLOBAL_DATA_SUCCESS: 'GET_GLOBAL_DATA_SUCCESS',
  GET_GLOBAL_DATA_FAILURE: 'GET_GLOBAL_DATA_FAILURE',

  GET_GEODATA: 'GET_GEODATA',
  GET_GEODATA_REQUEST: 'GET_GEODATA_REQUEST',
  GET_GEODATA_SUCCESS: 'GET_GEODATA_SUCCESS',
  GET_GEODATA_FAILURE: 'GET_GEODATA_FAILURE',

  GET_ZIP_CODE: 'GET_ZIP_CODE',
  GET_ZIP_CODE_REQUEST: 'GET_ZIP_CODE_REQUEST',
  GET_ZIP_CODE_SUCCESS: 'GET_ZIP_CODE_SUCCESS',
  GET_ZIP_CODE_FAILURE: 'GET_ZIP_CODE_FAILURE',

  GET_ARRIVE_TIME: 'GET_ARRIVE_TIME',
  GET_ARRIVE_TIME_REQUEST: 'GET_ARRIVE_TIME_REQUEST',
  GET_ARRIVE_TIME_SUCCESS: 'GET_ARRIVE_TIME_SUCCESS',
  GET_ARRIVE_TIME_FAILURE: 'GET_ARRIVE_TIME_FAILURE',

  UPLOAD_ATTACH_FILE: 'UPLOAD_ATTACH_FILE',
  UPLOAD_ATTACH_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
  UPLOAD_ATTACH_FILE_SUCCESS: 'UPLOAD_ATTACH_FILE_SUCCESS',
  UPLOAD_ATTACH_FILE_FAILURE: 'UPLOAD_ATTACH_FILE_FAILURE',
  
  GET_ADS: 'GET_ADS',
  GET_ADS_REQUEST: 'GET_ADS_REQUEST',
  GET_ADS_SUCCESS: 'GET_ADS_SUCCESS',
  GET_ADS_FAILURE: 'GET_ADS_FAILURE',

  ADD_ADS_SHOW: 'ADD_ADS_SHOW',
  ADD_ADS_SHOW_REQUEST: 'ADD_ADS_SHOW_REQUEST',
  ADD_ADS_SHOW_SUCCESS: 'ADD_ADS_SHOW_SUCCESS',
  ADD_ADS_SHOW_FAILURE: 'ADD_ADS_SHOW_FAILURE',

  ADD_ADS_CLICK: 'ADD_ADS_CLICK',
  ADD_ADS_CLICK_REQUEST: 'ADD_ADS_CLICK_REQUEST',
  ADD_ADS_CLICK_SUCCESS: 'ADD_ADS_CLICK_SUCCESS',
  ADD_ADS_CLICK_FAILURE: 'ADD_ADS_CLICK_FAILURE',

  CLOSE_ADS: 'CLOSE_ADS',
  CLOSE_ADS_REQUEST: 'CLOSE_ADS_REQUEST',
  CLOSE_ADS_SUCCESS: 'CLOSE_ADS_SUCCESS',
  CLOSE_ADS_FAILURE: 'CLOSE_ADS_FAILURE',

  SET_YEARS: 'SET_YEARS',
  RESET_GLOBAL: 'RESET_GLOBAL',
};
