export default {
  GET_JOB: 'GET_JOB',
  GET_JOB_REQUEST: 'GET_JOB_REQUEST',
  GET_JOB_SUCCESS: 'GET_JOB_SUCCESS',
  GET_JOB_FAILURE: 'GET_JOB_FAILURE',  

  GET_MY_JOBS: 'GET_MY_JOBS',
  GET_MY_JOBS_REQUEST: 'GET_MY_JOBS_REQUEST',
  GET_MY_JOBS_SUCCESS: 'GET_MY_JOBS_SUCCESS',
  GET_MY_JOBS_FAILURE: 'GET_MY_JOBS_FAILURE',  

  CREATE_NEW_JOB: 'CREATE_NEW_JOB',
  CREATE_NEW_JOB_REQUEST: 'CREATE_NEW_JOB_REQUEST',
  CREATE_NEW_JOB_SUCCESS: 'CREATE_NEW_JOB_SUCCESS',
  CREATE_NEW_JOB_FAILURE: 'CREATE_NEW_JOB_FAILURE',

  UPDATE_JOB: 'UPDATE_JOB',
  UPDATE_JOB_REQUEST: 'UPDATE_JOB_REQUEST',
  UPDATE_JOB_SUCCESS: 'UPDATE_JOB_SUCCESS',
  UPDATE_JOB_FAILURE: 'UPDATE_JOB_FAILURE',

  GET_FAVORITE_JOBS: 'GET_FAVORITE_JOBS',
  GET_FAVORITE_JOBS_REQUEST: 'GET_FAVORITE_JOBS_REQUEST',
  GET_FAVORITE_JOBS_SUCCESS: 'GET_FAVORITE_JOBS_SUCCESS',
  GET_FAVORITE_JOBS_FAILURE: 'GET_FAVORITE_JOBS_FAILURE',

  SEARCH_JOBS: 'SEARCH_JOBS',
  SEARCH_JOBS_REQUEST: 'SEARCH_JOBS_REQUEST',
  SEARCH_JOBS_SUCCESS: 'SEARCH_JOBS_SUCCESS',
  SEARCH_JOBS_FAILURE: 'SEARCH_JOBS_FAILURE',

  FAVORITE: 'FAVORITE',
  FAVORITE_REQUEST: 'FAVORITE_REQUEST',
  FAVORITE_SUCCESS: 'FAVORITE_SUCCESS',
  FAVORITE_FAILURE: 'FAVORITE_FAILURE',

  UNFAVORITE: 'UNFAVORITE',
  UNFAVORITE_REQUEST: 'UNFAVORITE_REQUEST',
  UNFAVORITE_SUCCESS: 'UNFAVORITE_SUCCESS',
  UNFAVORITE_FAILURE: 'UNFAVORITE_FAILURE',

  DELETE_PROJECT: 'DELETE_PROJECT',
  DELETE_PROJECT_REQUEST: 'DELETE_PROJECT_REQUEST',
  DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_FAILURE: 'DELETE_PROJECT_FAILURE',

  APPLY: 'APPLY',
  APPLY_REQUEST: 'APPLY_REQUEST',
  APPLY_SUCCESS: 'APPLY_SUCCESS',
  APPLY_FAILURE: 'APPLY_FAILURE',

  WITHDRAW_APPLY: 'WITHDRAW_APPLY',
  WITHDRAW_APPLY_REQUEST: 'WITHDRAW_APPLY_REQUEST',
  WITHDRAW_APPLY_SUCCESS: 'WITHDRAW_APPLY_SUCCESS',
  WITHDRAW_APPLY_FAILURE: 'WITHDRAW_APPLY_FAILURE',

  GET_APPLY_JOBS: 'GET_APPLY_JOBS',
  GET_APPLY_JOBS_REQUEST: 'GET_APPLY_JOBS_REQUEST',
  GET_APPLY_JOBS_SUCCESS: 'GET_APPLY_JOBS_SUCCESS',
  GET_APPLY_JOBS_FAILURE: 'GET_APPLY_JOBS_FAILURE',  

  DECLINE_APPLY: 'DECLINE_APPLY',
  DECLINE_APPLY_REQUEST: 'DECLINE_APPLY_REQUEST',
  DECLINE_APPLY_SUCCESS: 'DECLINE_APPLY_SUCCESS',
  DECLINE_APPLY_FAILURE: 'DECLINE_APPLY_FAILURE',

  HIRE: 'HIRE',
  HIRE_REQUEST: 'HIRE_REQUEST',
  HIRE_SUCCESS: 'HIRE_SUCCESS',
  HIRE_FAILURE: 'HIRE_FAILURE',

  CANCEL_JOB: 'CANCEL_JOB',
  CANCEL_JOB_REQUEST: 'CANCEL_JOB_REQUEST',
  CANCEL_JOB_SUCCESS: 'CANCEL_JOB_SUCCESS',
  CANCEL_JOB_FAILURE: 'CANCEL_JOB_FAILURE',

  PAY_JOB: 'PAY_JOB',
  PAY_JOB_REQUEST: 'PAY_JOB_REQUEST',
  PAY_JOB_SUCCESS: 'PAY_JOB_SUCCESS',
  PAY_JOB_FAILURE: 'PAY_JOB_FAILURE',

  WRITE_REVIEW: 'WRITE_REVIEW',
  WRITE_REVIEW_REQUEST: 'WRITE_REVIEW_REQUEST',
  WRITE_REVIEW_SUCCESS: 'WRITE_REVIEW_SUCCESS',
  WRITE_REVIEW_FAILURE: 'WRITE_REVIEW_FAILURE',

  RESET_JOB: 'RESET_JOB',
};
